# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clustering_ui_d.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1919, 907)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.comboBoxSingMul = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxSingMul.setObjectName("comboBoxSingMul")
        self.comboBoxSingMul.addItem("")
        self.comboBoxSingMul.addItem("")
        self.horizontalLayout_26.addWidget(self.comboBoxSingMul)
        self.pushButtonLoadSpec = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLoadSpec.setObjectName("pushButtonLoadSpec")
        self.horizontalLayout_26.addWidget(self.pushButtonLoadSpec)
        self.horizontalLayout_26.setStretch(0, 2)
        self.horizontalLayout_26.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEditDirSpectra = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditDirSpectra.setReadOnly(True)
        self.lineEditDirSpectra.setObjectName("lineEditDirSpectra")
        self.horizontalLayout_4.addWidget(self.lineEditDirSpectra)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_25.addWidget(self.label_2)
        self.lineEditFileNum = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditFileNum.setReadOnly(True)
        self.lineEditFileNum.setObjectName("lineEditFileNum")
        self.horizontalLayout_25.addWidget(self.lineEditFileNum)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_25.addWidget(self.label)
        self.lineEditTotal = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditTotal.setReadOnly(True)
        self.lineEditTotal.setObjectName("lineEditTotal")
        self.horizontalLayout_25.addWidget(self.lineEditTotal)
        self.verticalLayout.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.pushButtonLoadConc = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLoadConc.setObjectName("pushButtonLoadConc")
        self.horizontalLayout_24.addWidget(self.pushButtonLoadConc)
        self.pushButtonPrevious = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPrevious.setObjectName("pushButtonPrevious")
        self.horizontalLayout_24.addWidget(self.pushButtonPrevious)
        self.pushButtonNext = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonNext.setObjectName("pushButtonNext")
        self.horizontalLayout_24.addWidget(self.pushButtonNext)
        self.horizontalLayout_24.setStretch(0, 1)
        self.horizontalLayout_24.setStretch(1, 1)
        self.horizontalLayout_24.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_19.addWidget(self.label_5)
        self.lineEditDirPurest = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditDirPurest.setReadOnly(True)
        self.lineEditDirPurest.setObjectName("lineEditDirPurest")
        self.horizontalLayout_19.addWidget(self.lineEditDirPurest)
        self.verticalLayout.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEditFilename = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditFilename.setReadOnly(True)
        self.lineEditFilename.setObjectName("lineEditFilename")
        self.horizontalLayout_3.addWidget(self.lineEditFilename)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.lineEditLength = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditLength.setReadOnly(True)
        self.lineEditLength.setObjectName("lineEditLength")
        self.horizontalLayout_5.addWidget(self.lineEditLength)
        self.horizontalLayout_28.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEditWidth = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditWidth.setReadOnly(True)
        self.lineEditWidth.setObjectName("lineEditWidth")
        self.horizontalLayout_6.addWidget(self.lineEditWidth)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.lineEditHeight = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditHeight.setReadOnly(True)
        self.lineEditHeight.setObjectName("lineEditHeight")
        self.horizontalLayout_6.addWidget(self.lineEditHeight)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(2, 1)
        self.horizontalLayout_28.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_28)
        self.verticalLayout_15.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plot_specta = MplWidget(self.centralwidget)
        self.plot_specta.setObjectName("plot_specta")
        self.verticalLayout_2.addWidget(self.plot_specta)
        self.pushButtonExpandSpectra = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonExpandSpectra.setObjectName("pushButtonExpandSpectra")
        self.verticalLayout_2.addWidget(self.pushButtonExpandSpectra)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_15.addLayout(self.verticalLayout_2)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.comboBoxMethod = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxMethod.setObjectName("comboBoxMethod")
        self.comboBoxMethod.addItem("")
        self.comboBoxMethod.addItem("")
        self.comboBoxMethod.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBoxMethod)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.comboBoxCmaps = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxCmaps.setObjectName("comboBoxCmaps")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.comboBoxCmaps.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBoxCmaps)
        self.horizontalLayout_7.setStretch(1, 1)
        self.horizontalLayout_7.setStretch(3, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.labelMinwn = QtWidgets.QLabel(self.centralwidget)
        self.labelMinwn.setObjectName("labelMinwn")
        self.horizontalLayout_8.addWidget(self.labelMinwn)
        self.horizontalSliderWavenumber = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSliderWavenumber.setEnabled(False)
        self.horizontalSliderWavenumber.setMaximum(10000)
        self.horizontalSliderWavenumber.setSingleStep(1)
        self.horizontalSliderWavenumber.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderWavenumber.setObjectName("horizontalSliderWavenumber")
        self.horizontalLayout_8.addWidget(self.horizontalSliderWavenumber)
        self.labelMaxwn = QtWidgets.QLabel(self.centralwidget)
        self.labelMaxwn.setObjectName("labelMaxwn")
        self.horizontalLayout_8.addWidget(self.labelMaxwn)
        self.lineEditWavenumber = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditWavenumber.sizePolicy().hasHeightForWidth())
        self.lineEditWavenumber.setSizePolicy(sizePolicy)
        self.lineEditWavenumber.setReadOnly(True)
        self.lineEditWavenumber.setObjectName("lineEditWavenumber")
        self.horizontalLayout_8.addWidget(self.lineEditWavenumber)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.horizontalLayout_8.setStretch(1, 7)
        self.horizontalLayout_8.setStretch(3, 2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.verticalLayout_15.addLayout(self.verticalLayout_8)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.plot_visual = MplWidget(self.centralwidget)
        self.plot_visual.setObjectName("plot_visual")
        self.verticalLayout_4.addWidget(self.plot_visual)
        self.pushButtonExpandProjection = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonExpandProjection.setObjectName("pushButtonExpandProjection")
        self.verticalLayout_4.addWidget(self.pushButtonExpandProjection)
        self.horizontalLayout_13.addLayout(self.verticalLayout_4)
        self.horizontalLayout_13.setStretch(0, 3)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.plot_White = MplWidget(self.centralwidget)
        self.plot_White.setObjectName("plot_White")
        self.verticalLayout_13.addWidget(self.plot_White)
        self.pushButtonLoadWhite = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLoadWhite.setObjectName("pushButtonLoadWhite")
        self.verticalLayout_13.addWidget(self.pushButtonLoadWhite)
        self.horizontalLayout_21.addLayout(self.verticalLayout_13)
        self.horizontalLayout_21.setStretch(0, 3)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22.setStretch(0, 1)
        self.horizontalLayout_22.setStretch(1, 1)
        self.verticalLayout_15.addLayout(self.horizontalLayout_22)
        self.verticalLayout_15.setStretch(1, 1)
        self.verticalLayout_15.setStretch(3, 1)
        self.horizontalLayout_27.addLayout(self.verticalLayout_15)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.plotMultiVisual = MplWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.plotMultiVisual.sizePolicy().hasHeightForWidth())
        self.plotMultiVisual.setSizePolicy(sizePolicy)
        self.plotMultiVisual.setObjectName("plotMultiVisual")
        self.verticalLayout_3.addWidget(self.plotMultiVisual)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.comboBoxVisualize = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxVisualize.setObjectName("comboBoxVisualize")
        self.comboBoxVisualize.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBoxVisualize)
        self.pushButtonExpandVisual = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonExpandVisual.setObjectName("pushButtonExpandVisual")
        self.horizontalLayout_11.addWidget(self.pushButtonExpandVisual)
        self.horizontalLayout_11.setStretch(0, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.verticalLayout_3.setStretch(1, 1)
        self.horizontalLayout_20.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_11.addWidget(self.label_15)
        self.plotCluster = MplWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.plotCluster.sizePolicy().hasHeightForWidth())
        self.plotCluster.setSizePolicy(sizePolicy)
        self.plotCluster.setObjectName("plotCluster")
        self.verticalLayout_11.addWidget(self.plotCluster)
        self.pushButtonExpandCluster = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonExpandCluster.setEnabled(True)
        self.pushButtonExpandCluster.setObjectName("pushButtonExpandCluster")
        self.verticalLayout_11.addWidget(self.pushButtonExpandCluster)
        self.verticalLayout_11.setStretch(1, 1)
        self.verticalLayout_5.addLayout(self.verticalLayout_11)
        self.verticalLayout_5.setStretch(0, 1)
        self.horizontalLayout_20.addLayout(self.verticalLayout_5)
        self.horizontalLayout_20.setStretch(0, 1)
        self.horizontalLayout_20.setStretch(1, 1)
        self.verticalLayout_14.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_10.addWidget(self.label_16)
        self.plotAverage = MplWidget(self.centralwidget)
        self.plotAverage.setObjectName("plotAverage")
        self.verticalLayout_10.addWidget(self.plotAverage)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.pushButtonExpandAve = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonExpandAve.setObjectName("pushButtonExpandAve")
        self.horizontalLayout_23.addWidget(self.pushButtonExpandAve)
        self.pushButtonSaveSpectra = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSaveSpectra.setObjectName("pushButtonSaveSpectra")
        self.horizontalLayout_23.addWidget(self.pushButtonSaveSpectra)
        self.verticalLayout_10.addLayout(self.horizontalLayout_23)
        self.verticalLayout_10.setStretch(1, 1)
        self.horizontalLayout_18.addLayout(self.verticalLayout_10)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_6.addWidget(self.label_21)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout.addWidget(self.label_23)
        self.comboBoxC1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxC1.setEnabled(False)
        self.comboBoxC1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBoxC1.setObjectName("comboBoxC1")
        self.comboBoxC1.addItem("")
        self.comboBoxC1.addItem("")
        self.comboBoxC1.addItem("")
        self.comboBoxC1.addItem("")
        self.comboBoxC1.addItem("")
        self.comboBoxC1.addItem("")
        self.comboBoxC1.addItem("")
        self.comboBoxC1.addItem("")
        self.horizontalLayout.addWidget(self.comboBoxC1)
        self.lineEditA1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditA1.setEnabled(False)
        self.lineEditA1.setObjectName("lineEditA1")
        self.horizontalLayout.addWidget(self.lineEditA1)
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout.addWidget(self.label_29)
        self.comboBoxC5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxC5.setEnabled(False)
        self.comboBoxC5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBoxC5.setObjectName("comboBoxC5")
        self.comboBoxC5.addItem("")
        self.comboBoxC5.addItem("")
        self.comboBoxC5.addItem("")
        self.comboBoxC5.addItem("")
        self.comboBoxC5.addItem("")
        self.comboBoxC5.addItem("")
        self.comboBoxC5.addItem("")
        self.comboBoxC5.addItem("")
        self.horizontalLayout.addWidget(self.comboBoxC5)
        self.lineEditA5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditA5.setEnabled(False)
        self.lineEditA5.setObjectName("lineEditA5")
        self.horizontalLayout.addWidget(self.lineEditA5)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(4, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_2.addWidget(self.label_24)
        self.comboBoxC2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxC2.setEnabled(False)
        self.comboBoxC2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBoxC2.setObjectName("comboBoxC2")
        self.comboBoxC2.addItem("")
        self.comboBoxC2.addItem("")
        self.comboBoxC2.addItem("")
        self.comboBoxC2.addItem("")
        self.comboBoxC2.addItem("")
        self.comboBoxC2.addItem("")
        self.comboBoxC2.addItem("")
        self.comboBoxC2.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBoxC2)
        self.lineEditA2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditA2.setEnabled(False)
        self.lineEditA2.setObjectName("lineEditA2")
        self.horizontalLayout_2.addWidget(self.lineEditA2)
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_2.addWidget(self.label_27)
        self.comboBoxC6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxC6.setEnabled(False)
        self.comboBoxC6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBoxC6.setObjectName("comboBoxC6")
        self.comboBoxC6.addItem("")
        self.comboBoxC6.addItem("")
        self.comboBoxC6.addItem("")
        self.comboBoxC6.addItem("")
        self.comboBoxC6.addItem("")
        self.comboBoxC6.addItem("")
        self.comboBoxC6.addItem("")
        self.comboBoxC6.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBoxC6)
        self.lineEditA6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditA6.setEnabled(False)
        self.lineEditA6.setObjectName("lineEditA6")
        self.horizontalLayout_2.addWidget(self.lineEditA6)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(4, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_12.addWidget(self.label_25)
        self.comboBoxC3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxC3.setEnabled(False)
        self.comboBoxC3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBoxC3.setObjectName("comboBoxC3")
        self.comboBoxC3.addItem("")
        self.comboBoxC3.addItem("")
        self.comboBoxC3.addItem("")
        self.comboBoxC3.addItem("")
        self.comboBoxC3.addItem("")
        self.comboBoxC3.addItem("")
        self.comboBoxC3.addItem("")
        self.comboBoxC3.addItem("")
        self.horizontalLayout_12.addWidget(self.comboBoxC3)
        self.lineEditA3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditA3.setEnabled(False)
        self.lineEditA3.setObjectName("lineEditA3")
        self.horizontalLayout_12.addWidget(self.lineEditA3)
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_12.addWidget(self.label_30)
        self.comboBoxC7 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxC7.setEnabled(False)
        self.comboBoxC7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBoxC7.setObjectName("comboBoxC7")
        self.comboBoxC7.addItem("")
        self.comboBoxC7.addItem("")
        self.comboBoxC7.addItem("")
        self.comboBoxC7.addItem("")
        self.comboBoxC7.addItem("")
        self.comboBoxC7.addItem("")
        self.comboBoxC7.addItem("")
        self.comboBoxC7.addItem("")
        self.horizontalLayout_12.addWidget(self.comboBoxC7)
        self.lineEditA7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditA7.setEnabled(False)
        self.lineEditA7.setObjectName("lineEditA7")
        self.horizontalLayout_12.addWidget(self.lineEditA7)
        self.horizontalLayout_12.setStretch(1, 1)
        self.horizontalLayout_12.setStretch(4, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_14.addWidget(self.label_26)
        self.comboBoxC4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxC4.setEnabled(False)
        self.comboBoxC4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBoxC4.setObjectName("comboBoxC4")
        self.comboBoxC4.addItem("")
        self.comboBoxC4.addItem("")
        self.comboBoxC4.addItem("")
        self.comboBoxC4.addItem("")
        self.comboBoxC4.addItem("")
        self.comboBoxC4.addItem("")
        self.comboBoxC4.addItem("")
        self.comboBoxC4.addItem("")
        self.horizontalLayout_14.addWidget(self.comboBoxC4)
        self.lineEditA4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditA4.setEnabled(False)
        self.lineEditA4.setObjectName("lineEditA4")
        self.horizontalLayout_14.addWidget(self.lineEditA4)
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_14.addWidget(self.label_28)
        self.comboBoxC8 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxC8.setEnabled(False)
        self.comboBoxC8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBoxC8.setObjectName("comboBoxC8")
        self.comboBoxC8.addItem("")
        self.comboBoxC8.addItem("")
        self.comboBoxC8.addItem("")
        self.comboBoxC8.addItem("")
        self.comboBoxC8.addItem("")
        self.comboBoxC8.addItem("")
        self.comboBoxC8.addItem("")
        self.comboBoxC8.addItem("")
        self.horizontalLayout_14.addWidget(self.comboBoxC8)
        self.lineEditA8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditA8.setEnabled(False)
        self.lineEditA8.setObjectName("lineEditA8")
        self.horizontalLayout_14.addWidget(self.lineEditA8)
        self.horizontalLayout_14.setStretch(1, 1)
        self.horizontalLayout_14.setStretch(4, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.pushButtonRefresh = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonRefresh.setObjectName("pushButtonRefresh")
        self.verticalLayout_6.addWidget(self.pushButtonRefresh)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_15.addWidget(self.label_32)
        self.comboBoxColorBig = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxColorBig.setEnabled(False)
        self.comboBoxColorBig.setObjectName("comboBoxColorBig")
        self.comboBoxColorBig.addItem("")
        self.comboBoxColorBig.addItem("")
        self.comboBoxColorBig.addItem("")
        self.comboBoxColorBig.addItem("")
        self.comboBoxColorBig.addItem("")
        self.comboBoxColorBig.addItem("")
        self.comboBoxColorBig.addItem("")
        self.comboBoxColorBig.addItem("")
        self.horizontalLayout_15.addWidget(self.comboBoxColorBig)
        self.horizontalLayout_15.setStretch(1, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.verticalLayout_12.addLayout(self.verticalLayout_6)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_9.addWidget(self.label_20)
        self.comboBoxMethodCluster = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxMethodCluster.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBoxMethodCluster.setObjectName("comboBoxMethodCluster")
        self.comboBoxMethodCluster.addItem("")
        self.comboBoxMethodCluster.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBoxMethodCluster)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_10.addWidget(self.label_22)
        self.spinBoxNcluster = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxNcluster.setMinimum(1)
        self.spinBoxNcluster.setMaximum(30)
        self.spinBoxNcluster.setProperty("value", 8)
        self.spinBoxNcluster.setObjectName("spinBoxNcluster")
        self.horizontalLayout_10.addWidget(self.spinBoxNcluster)
        self.horizontalLayout_10.setStretch(1, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_16.addWidget(self.label_33)
        self.lineEditAnotClus = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditAnotClus.setReadOnly(True)
        self.lineEditAnotClus.setObjectName("lineEditAnotClus")
        self.horizontalLayout_16.addWidget(self.lineEditAnotClus)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.pushButtonCluster = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCluster.setObjectName("pushButtonCluster")
        self.verticalLayout_7.addWidget(self.pushButtonCluster)
        self.pushButtonReduce = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonReduce.setObjectName("pushButtonReduce")
        self.verticalLayout_7.addWidget(self.pushButtonReduce)
        self.verticalLayout_7.setStretch(0, 1)
        self.horizontalLayout_17.addLayout(self.verticalLayout_7)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem1)
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_9.addWidget(self.label_31)
        self.verticalLayout_9.setStretch(0, 1)
        self.horizontalLayout_17.addLayout(self.verticalLayout_9)
        self.verticalLayout_12.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18.addLayout(self.verticalLayout_12)
        self.horizontalLayout_18.setStretch(0, 3)
        self.horizontalLayout_18.setStretch(1, 1)
        self.verticalLayout_14.addLayout(self.horizontalLayout_18)
        self.verticalLayout_14.setStretch(0, 3)
        self.verticalLayout_14.setStretch(1, 1)
        self.horizontalLayout_27.addLayout(self.verticalLayout_14)
        self.horizontalLayout_27.setStretch(0, 1)
        self.horizontalLayout_27.setStretch(1, 3)
        self.gridLayout.addLayout(self.horizontalLayout_27, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBoxSingMul, self.pushButtonLoadSpec)
        MainWindow.setTabOrder(self.pushButtonLoadSpec, self.lineEditDirSpectra)
        MainWindow.setTabOrder(self.lineEditDirSpectra, self.lineEditFileNum)
        MainWindow.setTabOrder(self.lineEditFileNum, self.lineEditTotal)
        MainWindow.setTabOrder(self.lineEditTotal, self.pushButtonLoadConc)
        MainWindow.setTabOrder(self.pushButtonLoadConc, self.pushButtonNext)
        MainWindow.setTabOrder(self.pushButtonNext, self.lineEditDirPurest)
        MainWindow.setTabOrder(self.lineEditDirPurest, self.lineEditFilename)
        MainWindow.setTabOrder(self.lineEditFilename, self.lineEditLength)
        MainWindow.setTabOrder(self.lineEditLength, self.lineEditWidth)
        MainWindow.setTabOrder(self.lineEditWidth, self.lineEditHeight)
        MainWindow.setTabOrder(self.lineEditHeight, self.pushButtonExpandSpectra)
        MainWindow.setTabOrder(self.pushButtonExpandSpectra, self.comboBoxMethod)
        MainWindow.setTabOrder(self.comboBoxMethod, self.comboBoxCmaps)
        MainWindow.setTabOrder(self.comboBoxCmaps, self.horizontalSliderWavenumber)
        MainWindow.setTabOrder(self.horizontalSliderWavenumber, self.lineEditWavenumber)
        MainWindow.setTabOrder(self.lineEditWavenumber, self.pushButtonExpandProjection)
        MainWindow.setTabOrder(self.pushButtonExpandProjection, self.pushButtonLoadWhite)
        MainWindow.setTabOrder(self.pushButtonLoadWhite, self.comboBoxVisualize)
        MainWindow.setTabOrder(self.comboBoxVisualize, self.pushButtonExpandVisual)
        MainWindow.setTabOrder(self.pushButtonExpandVisual, self.pushButtonExpandAve)
        MainWindow.setTabOrder(self.pushButtonExpandAve, self.pushButtonSaveSpectra)
        MainWindow.setTabOrder(self.pushButtonSaveSpectra, self.pushButtonExpandCluster)
        MainWindow.setTabOrder(self.pushButtonExpandCluster, self.comboBoxC1)
        MainWindow.setTabOrder(self.comboBoxC1, self.lineEditA1)
        MainWindow.setTabOrder(self.lineEditA1, self.comboBoxC2)
        MainWindow.setTabOrder(self.comboBoxC2, self.lineEditA2)
        MainWindow.setTabOrder(self.lineEditA2, self.comboBoxC3)
        MainWindow.setTabOrder(self.comboBoxC3, self.lineEditA3)
        MainWindow.setTabOrder(self.lineEditA3, self.comboBoxC4)
        MainWindow.setTabOrder(self.comboBoxC4, self.lineEditA4)
        MainWindow.setTabOrder(self.lineEditA4, self.comboBoxC5)
        MainWindow.setTabOrder(self.comboBoxC5, self.lineEditA5)
        MainWindow.setTabOrder(self.lineEditA5, self.comboBoxC6)
        MainWindow.setTabOrder(self.comboBoxC6, self.lineEditA6)
        MainWindow.setTabOrder(self.lineEditA6, self.comboBoxC7)
        MainWindow.setTabOrder(self.comboBoxC7, self.lineEditA7)
        MainWindow.setTabOrder(self.lineEditA7, self.comboBoxC8)
        MainWindow.setTabOrder(self.comboBoxC8, self.lineEditA8)
        MainWindow.setTabOrder(self.lineEditA8, self.pushButtonRefresh)
        MainWindow.setTabOrder(self.pushButtonRefresh, self.comboBoxColorBig)
        MainWindow.setTabOrder(self.comboBoxColorBig, self.comboBoxMethodCluster)
        MainWindow.setTabOrder(self.comboBoxMethodCluster, self.spinBoxNcluster)
        MainWindow.setTabOrder(self.spinBoxNcluster, self.lineEditAnotClus)
        MainWindow.setTabOrder(self.lineEditAnotClus, self.pushButtonCluster)
        MainWindow.setTabOrder(self.pushButtonCluster, self.pushButtonReduce)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBoxSingMul.setItemText(0, _translate("MainWindow", "Multiple Files"))
        self.comboBoxSingMul.setItemText(1, _translate("MainWindow", "Single File"))
        self.pushButtonLoadSpec.setText(_translate("MainWindow", "Load Spectra"))
        self.label_4.setText(_translate("MainWindow", "Dir. spectra"))
        self.label_2.setText(_translate("MainWindow", "File Number "))
        self.label.setText(_translate("MainWindow", "Total .mat file"))
        self.pushButtonLoadConc.setText(_translate("MainWindow", "Load purest specra and concentration"))
        self.pushButtonPrevious.setText(_translate("MainWindow", "Previous"))
        self.pushButtonNext.setText(_translate("MainWindow", "Next"))
        self.label_5.setText(_translate("MainWindow", "Dir.purest"))
        self.label_3.setText(_translate("MainWindow", "Filename"))
        self.label_6.setText(_translate("MainWindow", "Length of Spectrum "))
        self.label_7.setText(_translate("MainWindow", "x"))
        self.label_8.setText(_translate("MainWindow", "Pixel"))
        self.pushButtonExpandSpectra.setText(_translate("MainWindow", "Expand"))
        self.label_9.setText(_translate("MainWindow", "Image Reconstruction Method"))
        self.comboBoxMethod.setItemText(0, _translate("MainWindow", "Total Intensity"))
        self.comboBoxMethod.setItemText(1, _translate("MainWindow", "Maximum Amplitude"))
        self.comboBoxMethod.setItemText(2, _translate("MainWindow", "Wavenumber "))
        self.label_10.setText(_translate("MainWindow", "Cmaps"))
        self.comboBoxCmaps.setItemText(0, _translate("MainWindow", "jet"))
        self.comboBoxCmaps.setItemText(1, _translate("MainWindow", "copper"))
        self.comboBoxCmaps.setItemText(2, _translate("MainWindow", "gray"))
        self.comboBoxCmaps.setItemText(3, _translate("MainWindow", "hsv"))
        self.comboBoxCmaps.setItemText(4, _translate("MainWindow", "hot"))
        self.comboBoxCmaps.setItemText(5, _translate("MainWindow", "cool"))
        self.comboBoxCmaps.setItemText(6, _translate("MainWindow", "summer"))
        self.comboBoxCmaps.setItemText(7, _translate("MainWindow", "winter"))
        self.comboBoxCmaps.setItemText(8, _translate("MainWindow", "autumn"))
        self.comboBoxCmaps.setItemText(9, _translate("MainWindow", "Set1"))
        self.comboBoxCmaps.setItemText(10, _translate("MainWindow", "gnuplot"))
        self.comboBoxCmaps.setItemText(11, _translate("MainWindow", "rainbow"))
        self.comboBoxCmaps.setItemText(12, _translate("MainWindow", "seismic"))
        self.comboBoxCmaps.setItemText(13, _translate("MainWindow", "pink"))
        self.comboBoxCmaps.setItemText(14, _translate("MainWindow", "spring"))
        self.comboBoxCmaps.setItemText(15, _translate("MainWindow", "Reds"))
        self.labelMinwn.setText(_translate("MainWindow", "1000"))
        self.labelMaxwn.setText(_translate("MainWindow", "1530"))
        self.label_11.setText(_translate("MainWindow", " (1/cm)"))
        self.pushButtonExpandProjection.setText(_translate("MainWindow", "Expand"))
        self.pushButtonLoadWhite.setText(_translate("MainWindow", "Load White"))
        self.label_12.setText(_translate("MainWindow", "Visualization"))
        self.comboBoxVisualize.setItemText(0, _translate("MainWindow", "Spectra and White Light Image"))
        self.pushButtonExpandVisual.setText(_translate("MainWindow", "Expand"))
        self.label_15.setText(_translate("MainWindow", "Cluster Image"))
        self.pushButtonExpandCluster.setText(_translate("MainWindow", "Expand"))
        self.label_16.setText(_translate("MainWindow", "Average Spectra of Each Cluster"))
        self.pushButtonExpandAve.setText(_translate("MainWindow", "Expand"))
        self.pushButtonSaveSpectra.setText(_translate("MainWindow", "Save Average Spectra"))
        self.label_21.setText(_translate("MainWindow", "Annotation for # Clusters < = 8"))
        self.label_23.setText(_translate("MainWindow", "#1"))
        self.comboBoxC1.setItemText(0, _translate("MainWindow", "red"))
        self.comboBoxC1.setItemText(1, _translate("MainWindow", "green"))
        self.comboBoxC1.setItemText(2, _translate("MainWindow", "yellow"))
        self.comboBoxC1.setItemText(3, _translate("MainWindow", "cyan"))
        self.comboBoxC1.setItemText(4, _translate("MainWindow", "black"))
        self.comboBoxC1.setItemText(5, _translate("MainWindow", "blue"))
        self.comboBoxC1.setItemText(6, _translate("MainWindow", "orange"))
        self.comboBoxC1.setItemText(7, _translate("MainWindow", "magenta"))
        self.label_29.setText(_translate("MainWindow", "#5"))
        self.comboBoxC5.setItemText(0, _translate("MainWindow", "black"))
        self.comboBoxC5.setItemText(1, _translate("MainWindow", "blue"))
        self.comboBoxC5.setItemText(2, _translate("MainWindow", "orange"))
        self.comboBoxC5.setItemText(3, _translate("MainWindow", "magenta"))
        self.comboBoxC5.setItemText(4, _translate("MainWindow", "red"))
        self.comboBoxC5.setItemText(5, _translate("MainWindow", "green"))
        self.comboBoxC5.setItemText(6, _translate("MainWindow", "yellow"))
        self.comboBoxC5.setItemText(7, _translate("MainWindow", "cyan"))
        self.label_24.setText(_translate("MainWindow", "#2"))
        self.comboBoxC2.setItemText(0, _translate("MainWindow", "green"))
        self.comboBoxC2.setItemText(1, _translate("MainWindow", "yellow"))
        self.comboBoxC2.setItemText(2, _translate("MainWindow", "cyan"))
        self.comboBoxC2.setItemText(3, _translate("MainWindow", "black"))
        self.comboBoxC2.setItemText(4, _translate("MainWindow", "blue"))
        self.comboBoxC2.setItemText(5, _translate("MainWindow", "orange"))
        self.comboBoxC2.setItemText(6, _translate("MainWindow", "magenta"))
        self.comboBoxC2.setItemText(7, _translate("MainWindow", "red"))
        self.label_27.setText(_translate("MainWindow", "#6"))
        self.comboBoxC6.setItemText(0, _translate("MainWindow", "blue"))
        self.comboBoxC6.setItemText(1, _translate("MainWindow", "orange"))
        self.comboBoxC6.setItemText(2, _translate("MainWindow", "magenta"))
        self.comboBoxC6.setItemText(3, _translate("MainWindow", "red"))
        self.comboBoxC6.setItemText(4, _translate("MainWindow", "green"))
        self.comboBoxC6.setItemText(5, _translate("MainWindow", "yellow"))
        self.comboBoxC6.setItemText(6, _translate("MainWindow", "cyan"))
        self.comboBoxC6.setItemText(7, _translate("MainWindow", "black"))
        self.label_25.setText(_translate("MainWindow", "#3"))
        self.comboBoxC3.setItemText(0, _translate("MainWindow", "yellow"))
        self.comboBoxC3.setItemText(1, _translate("MainWindow", "cyan"))
        self.comboBoxC3.setItemText(2, _translate("MainWindow", "black"))
        self.comboBoxC3.setItemText(3, _translate("MainWindow", "blue"))
        self.comboBoxC3.setItemText(4, _translate("MainWindow", "orange"))
        self.comboBoxC3.setItemText(5, _translate("MainWindow", "magenta"))
        self.comboBoxC3.setItemText(6, _translate("MainWindow", "red"))
        self.comboBoxC3.setItemText(7, _translate("MainWindow", "green"))
        self.label_30.setText(_translate("MainWindow", "#7"))
        self.comboBoxC7.setItemText(0, _translate("MainWindow", "orange"))
        self.comboBoxC7.setItemText(1, _translate("MainWindow", "red"))
        self.comboBoxC7.setItemText(2, _translate("MainWindow", "green"))
        self.comboBoxC7.setItemText(3, _translate("MainWindow", "yellow"))
        self.comboBoxC7.setItemText(4, _translate("MainWindow", "cyan"))
        self.comboBoxC7.setItemText(5, _translate("MainWindow", "black"))
        self.comboBoxC7.setItemText(6, _translate("MainWindow", "blue"))
        self.comboBoxC7.setItemText(7, _translate("MainWindow", "magenta"))
        self.label_26.setText(_translate("MainWindow", "#4"))
        self.comboBoxC4.setItemText(0, _translate("MainWindow", "cyan"))
        self.comboBoxC4.setItemText(1, _translate("MainWindow", "black"))
        self.comboBoxC4.setItemText(2, _translate("MainWindow", "blue"))
        self.comboBoxC4.setItemText(3, _translate("MainWindow", "orange"))
        self.comboBoxC4.setItemText(4, _translate("MainWindow", "magenta"))
        self.comboBoxC4.setItemText(5, _translate("MainWindow", "red"))
        self.comboBoxC4.setItemText(6, _translate("MainWindow", "green"))
        self.comboBoxC4.setItemText(7, _translate("MainWindow", "yellow"))
        self.label_28.setText(_translate("MainWindow", "#8"))
        self.comboBoxC8.setItemText(0, _translate("MainWindow", "magenta"))
        self.comboBoxC8.setItemText(1, _translate("MainWindow", "red"))
        self.comboBoxC8.setItemText(2, _translate("MainWindow", "green"))
        self.comboBoxC8.setItemText(3, _translate("MainWindow", "yellow"))
        self.comboBoxC8.setItemText(4, _translate("MainWindow", "cyan"))
        self.comboBoxC8.setItemText(5, _translate("MainWindow", "black"))
        self.comboBoxC8.setItemText(6, _translate("MainWindow", "blue"))
        self.comboBoxC8.setItemText(7, _translate("MainWindow", "orange"))
        self.pushButtonRefresh.setText(_translate("MainWindow", "Reset to original colors"))
        self.label_32.setText(_translate("MainWindow", "Annotation for # Clusters > 8"))
        self.comboBoxColorBig.setItemText(0, _translate("MainWindow", "Pastel1"))
        self.comboBoxColorBig.setItemText(1, _translate("MainWindow", "Pastel2"))
        self.comboBoxColorBig.setItemText(2, _translate("MainWindow", "Set1"))
        self.comboBoxColorBig.setItemText(3, _translate("MainWindow", "Set2"))
        self.comboBoxColorBig.setItemText(4, _translate("MainWindow", "Set3"))
        self.comboBoxColorBig.setItemText(5, _translate("MainWindow", "Paired"))
        self.comboBoxColorBig.setItemText(6, _translate("MainWindow", "tab10"))
        self.comboBoxColorBig.setItemText(7, _translate("MainWindow", "tab20"))
        self.label_20.setText(_translate("MainWindow", "Clustering Algorithm"))
        self.comboBoxMethodCluster.setItemText(0, _translate("MainWindow", "K-Means"))
        self.comboBoxMethodCluster.setItemText(1, _translate("MainWindow", "Mini Batch K-Means"))
        self.label_22.setText(_translate("MainWindow", "# Clusters "))
        self.label_33.setText(_translate("MainWindow", "# Annotated Clusters"))
        self.pushButtonCluster.setText(_translate("MainWindow", "Run "))
        self.pushButtonReduce.setText(_translate("MainWindow", "Reduce Cluster !"))
        self.label_31.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Credits;</span></p><p align=\"center\"><span style=\" font-size:8pt;\">Molecular Ecology, Microbial Ecology </span></p><p align=\"center\"><span style=\" font-size:8pt;\">and Evolutionary Genetics </span></p><p align=\"center\"><span style=\" font-size:8pt;\">&amp;</span></p><p align=\"center\"><span style=\" font-size:8pt;\">Computational Biology</span></p><p align=\"center\"><span style=\" font-size:8pt;\">and Biological Physics, Lund University</span></p></body></html>"))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

