#{% set data = load_setup_py_data() %}
{% set name = "octavvs" %}
{% set version = "0.0.30" %}
#{% set version = data.get('version') %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  - folder: .
    url: https://pypi.io/packages/source/p/pyshortcuts/pyshortcuts-1.7.tar.gz
  - folder: .
#    path: .
#    path: ../dist/{{ name }}-{{ version }}.tar.gz
    url: file://../dist/{{ name }}-{{ version }}.tar.gz
#    url: file:///home/carl/src/octavvs/dist/{{ name }}-{{ version }}.tar.gz
#    url: http://cbbp.thep.lu.se/~carl/octavvs-dist/{{ name }}-{{ version }}.tar.gz
#    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz

build:
  number: 0
  noarch: python
  entry_points:
    - oct_preprocessing = octavvs.preprocessing:main
    - oct_mcr_als = octavvs.mcr_als:main
    - oct_clustering = octavvs.clustering:main
    - oct_make_icons = octavvs.make_icons:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python=3.7
  run:
    - matplotlib
    - numpy=1.17
    - pyqt
    - pandas
    - pillow
    - python=3.7
    - scipy
    - scikit-learn
    - scikit-image
    - xlwt
    - dill

test:
  imports:
    - octavvs
    - octavvs.ui
    - octavvs.io
    - octavvs.algorithms
    - octavvs.reference_spectra
    - octavvs.mcr
    - octavvs.prep
    - octavvs.pymcr_new
  commands:
    - oct_preprocessing --help
    - oct_mcr_als --help
    - oct_clustering --help
    - oct_make_icons --help

about:
  home: https://github.com/ctroein/octavvs
  license: MIT
  license_family: MIT
  license_file: 
  summary: Open Chemometrics Toolkit for Analysis and Visualization of Vibrational Spectroscopy data
  doc_url: 
  dev_url: 
#  description: '{{ data.get('long_description').replace("'", "''") }}'
  description: 'OCTAVVS is a set of graphical tools for high-throughput preprocessing and analysis of vibrational spectroscopy data.
  
                More information can be found on the [OCTAVVS PyPI page](https://pypi.org/project/octavvs).
                '

extra:
  recipe-maintainers:
    - ctroein
